FROM algmprivsecops/jenkins-compose-lagooncli:v1.1

RUN curl -L "https://github.com/uselagoon/lagoon-cli/releases/download/v0.17.0/lagoon-cli-v0.17.0-linux-amd64" -o /usr/local/bin/lagoon && chmod +x /usr/local/bin/lagoon
